[workspace]
members = ["litchitool", "litchi-cli", "litchi-api"]

[workspace.dependencies]
tracing = { version = "0.1.37", features = ["attributes"] }
serde = { version = "1.0.174", features = ["derive"] }
serde_json = "1.0.103"
