name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
      env:
        LITCHI_USERNAME: ${{ secrets.LITCHI_USERNAME }}
        LITCHI_PASSWORD: ${{ secrets.LITCHI_PASSWORD }}
    - name: Release Build
      run: cargo build --release --verbose
    - name: Upload CLI artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: Litchi CLI # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/litchi-cli
        # The desired behavior if no files are found using the provided path.
        if-no-files-found: error # optional, default is warn

